// <auto-generated />
using System;
using Donkey.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Donkey.DAL.Migrations
{
    [DbContext(typeof(DonkeyDBContext))]
    partial class DonkeyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Donkey.DomainModels.FileExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("FileExtensions");
                });

            modelBuilder.Entity("Donkey.DomainModels.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExtensionId");

                    b.Property<string>("FilePath");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<long>("Size");

                    b.Property<DateTime?>("UploadedDate");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.ToTable("FileInfos");
                });

            modelBuilder.Entity("Donkey.DomainModels.FileInfo", b =>
                {
                    b.HasOne("Donkey.DomainModels.FileExtension", "Extension")
                        .WithMany("FileInfos")
                        .HasForeignKey("ExtensionId");
                });
#pragma warning restore 612, 618
        }
    }
}
